openapi: 3.0.1
info:
  title: BerryGelan API
  version: 1.0.0
  description: We are friendly banking API, trust us
  termsOfService: www.berry-gelan.se/tos
  contact:
    email: support@berry-gelan.se
    name: Support
    url: www.berry-gelan.se/support
  license:
    name: Licensing
    url: www.berry-gelan.se/licensing
servers:
  - url: http://localhost:3000/
    variables: {}
    description: local fake server
  - url: http://my-json-server.typicode.com/{gitaccount}/{reponame}
    variables:
      gitaccount:
        default: BerryGelan
        enum:
          - BerryGelan
          - otheraccountname
        description: various accounts
      api:
        default: api
        enum:
          - api
          - other
        description: repo name
    description: server with variables
paths:
  /users:
    summary: user level operations
    description: create and read users
    get:
      summary: fetch users
      description: retrieve users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
    post:
      summary: create user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserPostBody'
      responses:
        '201':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
  /users/{userId}:
    summary: specific user operation
    description: fetch, update, delete user
    get:
      summary: fetch user
      description: fetch user by id
      operationId: fetchUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            example: "1234abc"
      responses:
        '200':
          $ref: '#/components/responses/UserArrayResponseBody'
        default:
          description: Default error sample response
      tags:
        - users
components:
  responses:
    UserArrayResponseBody:
      description: user array response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
  requestBodies:
    UserPostBody:
      description: new user request
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    FullUser:
      allOf:
        - $ref: '#/components/schemas/PostNewUser'
        - type: object
          properties:
            id:
              type: string
              example: abc123
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: Tom
        score:
          type: integer
          example: 123
        active:
          type: boolean
          example: true
