# .github/workflows/test.yml

name: Test

on:
  push:
    branches: [ main ]

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec uts_14a714 --ci --verbose
      - name: Run test suites
        run: inso run test uts_14a714 --env env_env_7032d2 --ci
      - name: Generate declarative config
        run: inso generate config uts_14a714 --type declarative --ci
