# .github/workflows/test.yml

name: Test

on:
  push:
    branches: [ main ]

jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Lint
        run: inso lint spec "MyAPI" --ci --verbose
      - name: Run test suites
        run: inso run test "MyAPI" --env env_env_7032d2 --ci
